# Generated by Django 3.1.4 on 2020-12-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_answer_author'),
        ('pybo', '0002_auto_20201230_1930'),
    ]

    operations = [
    ]
